### ISSUE TITLE
Invalid directory (Java)

### ISSUE THREAD

**Issue by ChristineBlume** [HebiRobotics/MatlabInput#1]
Hi there, thanks for providing these functions. I am running Ubuntu 18.04 and Matlab 2018b, however I encounter the following issue when calling.

`HebiJoystick(1)`

`Warning: Invalid file or directory '/home/chrono5/MatlabInput-master/src/main/resources/matlab/%RELEASE_NAME%.jar'. `

Any idea how to solve this? Suggestions are highly appreciated...

**Comment by ennerf** [comment]
Did you try to run the sources without compiling? You can download pre-compiled releases at the link below

https://github.com/HebiRobotics/MatlabInput/releases
