### ISSUE TITLE
Stop echoing of characters

### ISSUE THREAD

**Issue by ljbusse** [HebiRobotics/MatlabInput#4]
I'm trying to use HebiKeyboard to sense the left and right arrow keys ONLY. Is it possible to suppress the echo of other keys in the command window??

**Comment by ennerf** [comment]
Sorry, I don't think so.

**Comment by ljbusse** [comment]
OK.. thanks for responding.

Larry Busse
Voice/Text: +1 513-549-4552

Sent with [Proton Mail](https://proton.me/) secure email.
